---
title: "489 Data"
author: "Preston Lyons"
date: "25/05/2021"
output:
  word_document: default
  html_document: default
---
```{r lib, include=FALSE}
library("tidyverse")
library("haven")
library("psych")
library("dplyr")
library("tidyr")
library("papaja")
library("sjPlot")
library("patchwork")
library("lubridate")
library("pmdplyr")
library("correlation")
library("ggraph")
library("kableExtra")
library("psych")
library("dplyr")
library("tidyr")
library("careless")
library("psych")
library("lme4")
library('lmerTest')
```

```{r datadownload, include=FALSE}
df <- read_sav("Your Beliefs About Memory, Disclosure, and Child Testimony_April 8, 2019_12.05.sav")
```

```{r data1, include=FALSE}
## Select the variables relevant to my study

df1 <- df %>%
  dplyr::select("Q35_1", "Q35_2",	"Q35_5",	"Q35_9", "Q35_12", "Q48_1",	"Q48_2",	"Q48_5", "Q48_9",	"Q48_12",	"Q49_1",	"Q49_2",	"Q49_5",	"Q49_9",	"Q49_12",	"Q50_1",	"Q50_2", "Q50_5",	"Q50_9",	"Q50_12", "Q51_1",	"Q51_2",	"Q51_5",	"Q51_9", "Q51_12",	"Q52_1",	"Q52_2",	"Q52_5",	"Q52_9",	"Q52_12", "Q59_1", "Q59_2", "Q59_5", "Q59_9", "Q59_12", "Q60_1", "Q60_2", "Q60_5", "Q60_9", "Q60_12", "Q61_1", "Q61_2", "Q61_5", "Q61_9", "Q61_12", "Q62_1", "Q62_2", "Q62_5", "Q62_9", "Q62_12", "Q63_1", "Q63_2", "Q63_5", "Q63_9", "Q63_12")

## Rename the variables so they can be worked with

df1 <- rename(df1, MemChild.TD.3to5 = Q35_1, MemChild.TD.6to11 = Q35_2, MemChild.ID = Q35_5, MemAdult.TD = Q35_9, MemAdult.ID = Q35_12, SugChild1.TD.3to5 = Q48_1, SugChild1.TD.6to11 = Q48_2, SugChild1.ID = Q48_5, SugAdult1.TD = Q48_9, SugAdult1.ID = Q48_12, SugChild2.TD.3to5 = Q49_1, SugChild2.TD.6to11 = Q49_2, SugChild2.ID = Q49_5, SugAdult2.TD = Q49_9, SugAdult2.ID = Q49_12, SugChild3.TD.3to5 = Q50_1, SugChild3.TD.6to11 = Q50_2, SugChild3.ID = Q50_5, SugAdult3.TD = Q50_9, SugAdult3.ID = Q50_12, SugChild4.TD.3to5 = Q51_1, SugChild4.TD.6to11 = Q51_2, SugChild4.ID = Q51_5, SugAdult4.TD = Q51_9, SugAdult4.ID = Q51_12, SugChild5.TD.3to5 = Q52_1, SugChild5.TD.6to11 = Q52_2, SugChild5.ID = Q52_5, SugAdult5.TD = Q52_9, SugAdult5.ID = Q52_12, TestChild1.TD.3to5 = Q59_1, TestChild1.TD.6to11 = Q59_2, TestChild1.ID = Q59_5, TestAdult1.TD = Q59_9, TestAdult1.ID = Q59_12, TestChild2.TD.3to5 = Q60_1, TestChild2.TD.6to11 = Q60_2, TestChild2.ID = Q60_5, TestAdult2.TD = Q60_9, TestAdult2.ID = Q60_12, TestChild3.TD.3to5 = Q61_1, TestChild3.TD.6to11 = Q61_2, TestChild3.ID = Q61_5, TestAdult3.TD = Q61_9, TestAdult3.ID = Q61_12, TestChild4.TD.3to5 = Q62_1, TestChild4.TD.6to11 = Q62_2, TestChild4.ID = Q62_5, TestAdult4.TD = Q62_9, TestAdult4.ID = Q62_12, TestChild5.TD.3to5 = Q63_1, TestChild5.TD.6to11 = Q63_2, TestChild5.ID = Q63_5, TestAdult5.TD = Q63_9, TestAdult5.ID = Q63_12)

## Amalgamate the 3 measures so they are further simplified

id_test_child <- paste0("TestChild",1:5,".ID")
id_mem_child <- paste0("MemChild.ID")
id_sug_child <- paste0("SugChild",1:5,".ID")

td_test_3_5 <- paste0("TestChild",1:5,".TD.3to5")
td_mem_3_5 <- paste0("MemChild.TD.3to5")
td_sug_3_5 <- paste0("SugChild",1:5,".TD.3to5")

td_test_6_11 <- paste0("TestChild",1:5,".TD.6to11")
td_mem_6_11 <- paste0("MemChild.TD.6to11")
td_sug_6_11 <- paste0("SugChild",1:5,".TD.6to11")

id_test_adult <- paste0("TestAdult",1:5,".ID")
id_mem_adult <- paste0("MemAdult.ID")
id_sug_adult <- paste0("SugAdult",1:5,".ID")

td_test_adult <- paste0("TestAdult",1:5,".TD")
td_mem_adult <- paste0("MemAdult.TD")
td_sug_adult <- paste0("SugAdult",1:5,".TD")

## Coalesce these measures into one simple value to make additional analyses easier to code

short <- 
c(id_test_child, id_mem_child, id_sug_child, td_test_3_5, td_mem_3_5, td_sug_3_5, td_test_6_11, td_mem_6_11, td_sug_6_11, id_test_adult, id_mem_adult, id_sug_adult, td_test_adult, td_mem_adult, td_sug_adult)
```

```{r data2, include=TRUE}
## Select the demographic variables and rename them

library(table1)
library(kableExtra)

df2 <- df %>%
  dplyr::select("Q6", "Q7",	"Q9",	"Q10")

df2 <- rename(df2, Age = Q6, Gender = Q7, Education_Level = Q9, Parent = Q10) %>%
  mutate(Age = factor(Age, 
                      levels = c(1,2,3,4,5,6),
                      labels = c("(18 – 24)", "(25 – 34)",
                                 "(35 – 44)", "(45 – 54)", "(55 – 64)",
                                 "(65+)")),
         Gender = factor(Gender, 
                         levels = c(1, 2, 3),
                         labels = c("Male", "Female", "Non-Binary")),
         Education_Level = factor(Education_Level,
                                  levels = c(1, 2, 3),
                                  labels = c("None", "Secondary", "Tertiary")),
         Parent =  factor(Parent,
                          levels = c(1, 2),
                          labels = c("Yes", "No")))

tabnz <- df2 %>%
  select(Age, Gender, Education_Level, Parent)

df2_described <- 
prettyR::describe(df2)
```

```{r knownresponsedata, include=FALSE}
## Take out the DK responses


df1[,paste0(short, "_bin")] <- lapply(df1[,short], function(x){
  car::recode(x, "1 = 0; 2 = 0; 3 = 0; 4 = 0; 5 = 0; 6 = 0; 7 = 1")})

df1[,short] <- lapply(df1[,short], function(x){
  car::recode(x, "1 = 1; 2 = 2; 3 = 3; 4 = 4; 5 = 5; 6 = 6; else = NA")})

```

```{r data4, include=TRUE}
## Descriptive Statistics

df1$id_test_child <- rowMeans(df1[id_test_child], na.rm = T)
df1$id_mem_child <- rowMeans(df1[id_mem_child], na.rm = T)
df1$id_sug_child <- rowMeans(df1[id_sug_child], na.rm = T)

df1$td_test_3_5 <- rowMeans(df1[td_test_3_5], na.rm = T)
df1$td_mem_3_5 <- rowMeans(df1[td_mem_3_5], na.rm = T)
df1$td_sug_3_5 <- rowMeans(df1[td_sug_3_5], na.rm = T)

df1$td_test_6_11 <- rowMeans(df1[td_test_6_11], na.rm = T)
df1$td_mem_6_11 <- rowMeans(df1[td_mem_6_11], na.rm = T)
df1$td_sug_6_11 <- rowMeans(df1[td_sug_6_11], na.rm = T)

df1$id_test_adult <- rowMeans(df1[id_test_adult], na.rm = T)
df1$id_mem_adult <- rowMeans(df1[id_mem_adult], na.rm = T)
df1$id_sug_adult <- rowMeans(df1[id_sug_adult], na.rm = T)

df1$td_test_adult <- rowMeans(df1[td_test_adult], na.rm = T)
df1$td_mem_adult <- rowMeans(df1[td_mem_adult], na.rm = T)
df1$td_sug_adult <- rowMeans(df1[td_sug_adult], na.rm = T)

domain_list <- list("id_mem_child",
                  "id_test_child", 
                  "id_sug_child",
                  "td_mem_3_5",
                  "td_test_3_5",
                  "td_sug_3_5",
                  "td_mem_6_11",
                  "td_test_6_11",
                  "td_sug_6_11",
                  "id_mem_adult",
                  "id_test_adult",
                  "id_sug_adult",
                  "td_mem_adult",
                  "td_test_adult",
                  "td_sug_adult")

measure_names <- c("Memory - CWID",
                   "Ability to Testify - CWID",
                   "Suggestibility - CWID",
                   "Memory - TD 3-5 year olds",
                   "Ability to Testify in Court - TD 3-5 year olds",
                   "Suggestibility - TD 3-5 year olds",
                   "Memory - TD 6-11 year olds",
                   "Ability to Testify in Court - TD 6-11 year olds",
                   "Suggestibility - TD 6-11 year olds",
                   "Memory - AWID",
                   "Ability to Testify - AWID",
                   "Suggestibility - AWID",
                   "Memory - TD Adult",
                   "Ability to Testify - TD Adult",
                   "Suggestibility - TD Adult"
                   )

domain_out <- 
lapply(domain_list, function(x){
  data.frame(Mean = round(mean(df1[[x]], na.rm = T), 2),
             SD = round(sd(df1[[x]], na.rm = T), 2)
             )
  }) %>%
  do.call(rbind, .) %>%
  cbind(measure_names, .)

apa_table(domain_out, caption = "Means and standard deviations of measures in the study")
```

```{r reliability, include=FALSE}
measure_list <- list(id_test_child, 
                  id_sug_child,
                  td_test_3_5,
                  td_sug_3_5,
                  td_test_6_11,
                  td_sug_6_11,
                  id_test_adult,
                  id_sug_adult,
                  td_test_adult,
                  td_sug_adult)

measure_names <- c("Ability to Testify - CWID",
                   "Suggestibility - CWID",
                   "Ability to Testify in Court - TD 3-5 year olds",
                   "Suggestibility - TD 3-5 year olds",
                   "Ability to Testify in Court - TD 6-11 year olds",
                   "Suggestibility - TD 6-11 year olds",
                   "Ability to Testify - AWID",
                   "Suggestibility - AWID",
                   "Ability to Testify - TD Adult",
                   "Suggestibility - TD Adult"
                   )

rel_list <- 
lapply(measure_list, function(x){
  scale_out <- ufs::scaleStructure(df1[c(x)])
  data.frame(alpha = scale_out$output$cronbach.alpha,
             omega = scale_out$output$omega.psych,
             H = scale_out$output$coefficientH)
  }) %>%
  do.call(rbind, .) %>%
  cbind(measure_names, .)

apa_table(rel_list)
```

```{r lemranalysis, include=TRUE}
## LEMR (Linear Effects Mixed Regression)
df1$id <- paste0("id_", 1:nrow(df1))
library(lme4)
library(lmerTest)
library(tidyverse)
library(scales)

df1_long <- df1[c("id_test_child", "id_mem_child", "id_sug_child", "td_test_3_5", "td_mem_3_5", "td_sug_3_5", "td_test_6_11", "td_mem_6_11", "td_sug_6_11", "id_test_adult", "id_mem_adult", "id_sug_adult", "td_test_adult", "td_mem_adult", "td_sug_adult", "id")] %>%
  pivot_longer(., -id) %>%
  separate(., "name", into = c("type", "cat", "age", "age2")) %>%
  mutate(., target = paste0(type, age)) %>%
  mutate(., target = factor(target, levels = c("td3", "idchild", "td6", "idadult", "tdadult")))

lmer_out <- lmer("value ~ target * cat + (1|id)", data = df1_long)

sjPlot::plot_model(lmer_out, type =  "int") +
    labs(title = "Jurors' Beliefs of Witnesses With and Without ID's",
       x = "Measures",
       y = "Averaged Scores") +
    labs(color = "Measures") +
    scale_color_manual(values = c("#989E21", "#F0AD32", "#7AF0F0"), labels = c("Memory", "Suggestability", "Ability to Testify")) +
       scale_x_continuous(labels=c("td3" = "TD EC",
         "idchild" = "CWID",
         "td6" = "TD MC",
         "idadult" = "AWID",
         "tdadult" = "TD Adult"))

report::report(lmer_out)

# Try to get estimated marginal means from the emmeans package

emdf <- emmeans::emmeans(lmer_out, specs = pairwise ~ target:cat)

emdf1 <- emdf$contrasts %>%
         data.frame() %>%
         dplyr::select(., contrast, estimate, p.value) %>%
         mutate(p.value = round(p.value, 3))

report::report(emdf1)
```

```{r dkanalyses, include=TRUE}
## Analyse the DK responses

df1$dn_id <- rowMeans(df1[paste0(c(id_test_child, id_mem_child, id_sug_child), "_bin")])
df1$dn_td <- rowMeans(df1[paste0(c(td_test_3_5, td_mem_3_5, td_sug_3_5, td_test_6_11, td_mem_6_11, td_sug_6_11), "_bin")])
df1$dn_id_ad <- rowMeans(df1[paste0(c(id_test_adult, id_mem_adult, id_sug_adult), "_bin")])
df1$dn_td_ad <- rowMeans(df1[paste0(c(td_test_adult, td_mem_adult, td_sug_adult), "_bin")])

dn_long <- 
  df1 %>%
  select(., dn_id, dn_td, dn_id_ad, dn_td_ad, id) %>%
  pivot_longer(., -id)

lmer_out <- lmer(value ~ name + (1|id), dn_long)

lm_out <- lm(value ~ name , dn_long)

sjPlot::plot_model(lmer_out, type = "pred")$name +
    labs(title = "Graphical Summary Evaluation and Don't Know Scores for Each Age-Group",
       x = "Coalesced Child and Adult Scores With and Without ID",
       y = "Averaged Values") +
    scale_x_continuous(labels=c("dn_id" = "CWID",
         "dn_id_ad" = "AWID",
         "dn_td" = "TD Children",
         "dn_td_ad" = "TD Adults"))+
    aes(color = "green") +
  theme(legend.position = "none")
    
summary(lmer_out)
summary(lm_out)

emmeans::emmeans(lmer_out, pairwise ~ name)
```

```{r referencing, include=FALSE}
## Referencing Packages Used Before 3/6/21

report::cite_packages()

## Referencing FUrther Packages Used After 3/6/21

citation("emmeans")
```





